global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: store-backend-local
    metrics_path: /metrics
    static_configs:
      - targets:
          - store-backend:8080
